# Generated by Django 4.1.7 on 2024-12-09 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_alter_category_info_cat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category_info",
            options={"ordering": ["-date"]},
        ),
    ]
